#!/usr/bin/env bash
# Author: https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer
set -x
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/workspace/ -mindepth 2 -maxdepth 2 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi
echo $select
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds $selected_name -c $selected
    tmux split-window -t $selected_name:1.1 -hl 1
    tmux split-window -t $selected_name:1.2 -vl 1
    tmux send-keys -t $selected_name:1.1 "nvim ." Enter
    tmux send-keys -t $selected_name:1.2 "cd $selected" Enter
    tmux send-keys -t $selected_name:1.3 "cd $selected && ll && git s" Enter
    tmux attach-session -t $selected_name
    # tmss $selected $selected_name
    # selected="~/workspace/02_keypay/configuration-management"
    # selected_name="configuration-management"
    # selected=$1
    # selected_name=$2
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    tmux split-window -t $selected_name:1.1 -hl 80
    tmux split-window -t $selected_name:1.2 -vl 30
    tmux send-keys -t $selected_name:1.1 "nvim ." Enter
    tmux send-keys -t $selected_name:1.2 "cd $selected" Enter
    tmux send-keys -t $selected_name:1.3 "cd $selected && ll && git s" Enter
fi

tmux switch-client -t $selected_name
