#!/usr/bin/env bash
# Author: https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer
set -x
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/workspace/ -mindepth 2 -maxdepth 2 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi
echo $select
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

_sessionizer_create() {
    tmux new-session -ds $selected_name -c $selected
    tmux split-window -t $selected_name:1.1 -h -l 10%
    tmux split-window -t $selected_name:1.2 -v -l 30%
    tmux send-keys -t $selected_name:1.1 "nvim ." Enter
    tmux send-keys -t $selected_name:1.2 "cd $selected" Enter
    tmux send-keys -t $selected_name:1.3 "cd $selected && ll && git s" Enter
}

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    _sessionizer_create
    tmux attach-session -t $selected_name
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    _sessionizer_create
fi

tmux switch-client -t $selected_name
